//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapApp.Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.AtmServicesSoap")]
    public interface AtmServicesSoap {
        
        // CODEGEN: Generating message contract since element name IBAN from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WithDrawMoney", ReplyAction="*")]
        SoapApp.Client.ServiceReference1.WithDrawMoneyResponse WithDrawMoney(SoapApp.Client.ServiceReference1.WithDrawMoneyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WithDrawMoney", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapApp.Client.ServiceReference1.WithDrawMoneyResponse> WithDrawMoneyAsync(SoapApp.Client.ServiceReference1.WithDrawMoneyRequest request);
        
        // CODEGEN: Generating message contract since element name IBAN from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DepositMoney", ReplyAction="*")]
        SoapApp.Client.ServiceReference1.DepositMoneyResponse DepositMoney(SoapApp.Client.ServiceReference1.DepositMoneyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DepositMoney", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapApp.Client.ServiceReference1.DepositMoneyResponse> DepositMoneyAsync(SoapApp.Client.ServiceReference1.DepositMoneyRequest request);
        
        // CODEGEN: Generating message contract since element name senderIBAN from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EFT", ReplyAction="*")]
        SoapApp.Client.ServiceReference1.EFTResponse EFT(SoapApp.Client.ServiceReference1.EFTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EFT", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapApp.Client.ServiceReference1.EFTResponse> EFTAsync(SoapApp.Client.ServiceReference1.EFTRequest request);
        
        // CODEGEN: Generating message contract since element name ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveCustomer", ReplyAction="*")]
        SoapApp.Client.ServiceReference1.SaveCustomerResponse SaveCustomer(SoapApp.Client.ServiceReference1.SaveCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapApp.Client.ServiceReference1.SaveCustomerResponse> SaveCustomerAsync(SoapApp.Client.ServiceReference1.SaveCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OpenAnAccount", ReplyAction="*")]
        SoapApp.Client.ServiceReference1.OpenAnAccountResponse OpenAnAccount(SoapApp.Client.ServiceReference1.OpenAnAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OpenAnAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapApp.Client.ServiceReference1.OpenAnAccountResponse> OpenAnAccountAsync(SoapApp.Client.ServiceReference1.OpenAnAccountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WithDrawMoneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WithDrawMoney", Namespace="http://tempuri.org/", Order=0)]
        public SoapApp.Client.ServiceReference1.WithDrawMoneyRequestBody Body;
        
        public WithDrawMoneyRequest() {
        }
        
        public WithDrawMoneyRequest(SoapApp.Client.ServiceReference1.WithDrawMoneyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WithDrawMoneyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IBAN;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float amount;
        
        public WithDrawMoneyRequestBody() {
        }
        
        public WithDrawMoneyRequestBody(string IBAN, float amount) {
            this.IBAN = IBAN;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WithDrawMoneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WithDrawMoneyResponse", Namespace="http://tempuri.org/", Order=0)]
        public SoapApp.Client.ServiceReference1.WithDrawMoneyResponseBody Body;
        
        public WithDrawMoneyResponse() {
        }
        
        public WithDrawMoneyResponse(SoapApp.Client.ServiceReference1.WithDrawMoneyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WithDrawMoneyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool WithDrawMoneyResult;
        
        public WithDrawMoneyResponseBody() {
        }
        
        public WithDrawMoneyResponseBody(bool WithDrawMoneyResult) {
            this.WithDrawMoneyResult = WithDrawMoneyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DepositMoneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DepositMoney", Namespace="http://tempuri.org/", Order=0)]
        public SoapApp.Client.ServiceReference1.DepositMoneyRequestBody Body;
        
        public DepositMoneyRequest() {
        }
        
        public DepositMoneyRequest(SoapApp.Client.ServiceReference1.DepositMoneyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DepositMoneyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IBAN;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float amount;
        
        public DepositMoneyRequestBody() {
        }
        
        public DepositMoneyRequestBody(string IBAN, float amount) {
            this.IBAN = IBAN;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DepositMoneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DepositMoneyResponse", Namespace="http://tempuri.org/", Order=0)]
        public SoapApp.Client.ServiceReference1.DepositMoneyResponseBody Body;
        
        public DepositMoneyResponse() {
        }
        
        public DepositMoneyResponse(SoapApp.Client.ServiceReference1.DepositMoneyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DepositMoneyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DepositMoneyResult;
        
        public DepositMoneyResponseBody() {
        }
        
        public DepositMoneyResponseBody(bool DepositMoneyResult) {
            this.DepositMoneyResult = DepositMoneyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EFTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EFT", Namespace="http://tempuri.org/", Order=0)]
        public SoapApp.Client.ServiceReference1.EFTRequestBody Body;
        
        public EFTRequest() {
        }
        
        public EFTRequest(SoapApp.Client.ServiceReference1.EFTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EFTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string senderIBAN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string recipientIBAN;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float amount;
        
        public EFTRequestBody() {
        }
        
        public EFTRequestBody(string senderIBAN, string recipientIBAN, float amount) {
            this.senderIBAN = senderIBAN;
            this.recipientIBAN = recipientIBAN;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EFTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EFTResponse", Namespace="http://tempuri.org/", Order=0)]
        public SoapApp.Client.ServiceReference1.EFTResponseBody Body;
        
        public EFTResponse() {
        }
        
        public EFTResponse(SoapApp.Client.ServiceReference1.EFTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EFTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EFTResult;
        
        public EFTResponseBody() {
        }
        
        public EFTResponseBody(bool EFTResult) {
            this.EFTResult = EFTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveCustomer", Namespace="http://tempuri.org/", Order=0)]
        public SoapApp.Client.ServiceReference1.SaveCustomerRequestBody Body;
        
        public SaveCustomerRequest() {
        }
        
        public SaveCustomerRequest(SoapApp.Client.ServiceReference1.SaveCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName;
        
        public SaveCustomerRequestBody() {
        }
        
        public SaveCustomerRequestBody(string ID, string firstName, string lastName) {
            this.ID = ID;
            this.firstName = firstName;
            this.lastName = lastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public SoapApp.Client.ServiceReference1.SaveCustomerResponseBody Body;
        
        public SaveCustomerResponse() {
        }
        
        public SaveCustomerResponse(SoapApp.Client.ServiceReference1.SaveCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaveCustomerResult;
        
        public SaveCustomerResponseBody() {
        }
        
        public SaveCustomerResponseBody(bool SaveCustomerResult) {
            this.SaveCustomerResult = SaveCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenAnAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenAnAccount", Namespace="http://tempuri.org/", Order=0)]
        public SoapApp.Client.ServiceReference1.OpenAnAccountRequestBody Body;
        
        public OpenAnAccountRequest() {
        }
        
        public OpenAnAccountRequest(SoapApp.Client.ServiceReference1.OpenAnAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OpenAnAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string customerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IBAN;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float balance;
        
        public OpenAnAccountRequestBody() {
        }
        
        public OpenAnAccountRequestBody(string id, string customerId, string IBAN, float balance) {
            this.id = id;
            this.customerId = customerId;
            this.IBAN = IBAN;
            this.balance = balance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenAnAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenAnAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public SoapApp.Client.ServiceReference1.OpenAnAccountResponseBody Body;
        
        public OpenAnAccountResponse() {
        }
        
        public OpenAnAccountResponse(SoapApp.Client.ServiceReference1.OpenAnAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OpenAnAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool OpenAnAccountResult;
        
        public OpenAnAccountResponseBody() {
        }
        
        public OpenAnAccountResponseBody(bool OpenAnAccountResult) {
            this.OpenAnAccountResult = OpenAnAccountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AtmServicesSoapChannel : SoapApp.Client.ServiceReference1.AtmServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AtmServicesSoapClient : System.ServiceModel.ClientBase<SoapApp.Client.ServiceReference1.AtmServicesSoap>, SoapApp.Client.ServiceReference1.AtmServicesSoap {
        
        public AtmServicesSoapClient() {
        }
        
        public AtmServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AtmServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AtmServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AtmServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapApp.Client.ServiceReference1.WithDrawMoneyResponse SoapApp.Client.ServiceReference1.AtmServicesSoap.WithDrawMoney(SoapApp.Client.ServiceReference1.WithDrawMoneyRequest request) {
            return base.Channel.WithDrawMoney(request);
        }
        
        public bool WithDrawMoney(string IBAN, float amount) {
            SoapApp.Client.ServiceReference1.WithDrawMoneyRequest inValue = new SoapApp.Client.ServiceReference1.WithDrawMoneyRequest();
            inValue.Body = new SoapApp.Client.ServiceReference1.WithDrawMoneyRequestBody();
            inValue.Body.IBAN = IBAN;
            inValue.Body.amount = amount;
            SoapApp.Client.ServiceReference1.WithDrawMoneyResponse retVal = ((SoapApp.Client.ServiceReference1.AtmServicesSoap)(this)).WithDrawMoney(inValue);
            return retVal.Body.WithDrawMoneyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapApp.Client.ServiceReference1.WithDrawMoneyResponse> SoapApp.Client.ServiceReference1.AtmServicesSoap.WithDrawMoneyAsync(SoapApp.Client.ServiceReference1.WithDrawMoneyRequest request) {
            return base.Channel.WithDrawMoneyAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapApp.Client.ServiceReference1.WithDrawMoneyResponse> WithDrawMoneyAsync(string IBAN, float amount) {
            SoapApp.Client.ServiceReference1.WithDrawMoneyRequest inValue = new SoapApp.Client.ServiceReference1.WithDrawMoneyRequest();
            inValue.Body = new SoapApp.Client.ServiceReference1.WithDrawMoneyRequestBody();
            inValue.Body.IBAN = IBAN;
            inValue.Body.amount = amount;
            return ((SoapApp.Client.ServiceReference1.AtmServicesSoap)(this)).WithDrawMoneyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapApp.Client.ServiceReference1.DepositMoneyResponse SoapApp.Client.ServiceReference1.AtmServicesSoap.DepositMoney(SoapApp.Client.ServiceReference1.DepositMoneyRequest request) {
            return base.Channel.DepositMoney(request);
        }
        
        public bool DepositMoney(string IBAN, float amount) {
            SoapApp.Client.ServiceReference1.DepositMoneyRequest inValue = new SoapApp.Client.ServiceReference1.DepositMoneyRequest();
            inValue.Body = new SoapApp.Client.ServiceReference1.DepositMoneyRequestBody();
            inValue.Body.IBAN = IBAN;
            inValue.Body.amount = amount;
            SoapApp.Client.ServiceReference1.DepositMoneyResponse retVal = ((SoapApp.Client.ServiceReference1.AtmServicesSoap)(this)).DepositMoney(inValue);
            return retVal.Body.DepositMoneyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapApp.Client.ServiceReference1.DepositMoneyResponse> SoapApp.Client.ServiceReference1.AtmServicesSoap.DepositMoneyAsync(SoapApp.Client.ServiceReference1.DepositMoneyRequest request) {
            return base.Channel.DepositMoneyAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapApp.Client.ServiceReference1.DepositMoneyResponse> DepositMoneyAsync(string IBAN, float amount) {
            SoapApp.Client.ServiceReference1.DepositMoneyRequest inValue = new SoapApp.Client.ServiceReference1.DepositMoneyRequest();
            inValue.Body = new SoapApp.Client.ServiceReference1.DepositMoneyRequestBody();
            inValue.Body.IBAN = IBAN;
            inValue.Body.amount = amount;
            return ((SoapApp.Client.ServiceReference1.AtmServicesSoap)(this)).DepositMoneyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapApp.Client.ServiceReference1.EFTResponse SoapApp.Client.ServiceReference1.AtmServicesSoap.EFT(SoapApp.Client.ServiceReference1.EFTRequest request) {
            return base.Channel.EFT(request);
        }
        
        public bool EFT(string senderIBAN, string recipientIBAN, float amount) {
            SoapApp.Client.ServiceReference1.EFTRequest inValue = new SoapApp.Client.ServiceReference1.EFTRequest();
            inValue.Body = new SoapApp.Client.ServiceReference1.EFTRequestBody();
            inValue.Body.senderIBAN = senderIBAN;
            inValue.Body.recipientIBAN = recipientIBAN;
            inValue.Body.amount = amount;
            SoapApp.Client.ServiceReference1.EFTResponse retVal = ((SoapApp.Client.ServiceReference1.AtmServicesSoap)(this)).EFT(inValue);
            return retVal.Body.EFTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapApp.Client.ServiceReference1.EFTResponse> SoapApp.Client.ServiceReference1.AtmServicesSoap.EFTAsync(SoapApp.Client.ServiceReference1.EFTRequest request) {
            return base.Channel.EFTAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapApp.Client.ServiceReference1.EFTResponse> EFTAsync(string senderIBAN, string recipientIBAN, float amount) {
            SoapApp.Client.ServiceReference1.EFTRequest inValue = new SoapApp.Client.ServiceReference1.EFTRequest();
            inValue.Body = new SoapApp.Client.ServiceReference1.EFTRequestBody();
            inValue.Body.senderIBAN = senderIBAN;
            inValue.Body.recipientIBAN = recipientIBAN;
            inValue.Body.amount = amount;
            return ((SoapApp.Client.ServiceReference1.AtmServicesSoap)(this)).EFTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapApp.Client.ServiceReference1.SaveCustomerResponse SoapApp.Client.ServiceReference1.AtmServicesSoap.SaveCustomer(SoapApp.Client.ServiceReference1.SaveCustomerRequest request) {
            return base.Channel.SaveCustomer(request);
        }
        
        public bool SaveCustomer(string ID, string firstName, string lastName) {
            SoapApp.Client.ServiceReference1.SaveCustomerRequest inValue = new SoapApp.Client.ServiceReference1.SaveCustomerRequest();
            inValue.Body = new SoapApp.Client.ServiceReference1.SaveCustomerRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            SoapApp.Client.ServiceReference1.SaveCustomerResponse retVal = ((SoapApp.Client.ServiceReference1.AtmServicesSoap)(this)).SaveCustomer(inValue);
            return retVal.Body.SaveCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapApp.Client.ServiceReference1.SaveCustomerResponse> SoapApp.Client.ServiceReference1.AtmServicesSoap.SaveCustomerAsync(SoapApp.Client.ServiceReference1.SaveCustomerRequest request) {
            return base.Channel.SaveCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapApp.Client.ServiceReference1.SaveCustomerResponse> SaveCustomerAsync(string ID, string firstName, string lastName) {
            SoapApp.Client.ServiceReference1.SaveCustomerRequest inValue = new SoapApp.Client.ServiceReference1.SaveCustomerRequest();
            inValue.Body = new SoapApp.Client.ServiceReference1.SaveCustomerRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            return ((SoapApp.Client.ServiceReference1.AtmServicesSoap)(this)).SaveCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapApp.Client.ServiceReference1.OpenAnAccountResponse SoapApp.Client.ServiceReference1.AtmServicesSoap.OpenAnAccount(SoapApp.Client.ServiceReference1.OpenAnAccountRequest request) {
            return base.Channel.OpenAnAccount(request);
        }
        
        public bool OpenAnAccount(string id, string customerId, string IBAN, float balance) {
            SoapApp.Client.ServiceReference1.OpenAnAccountRequest inValue = new SoapApp.Client.ServiceReference1.OpenAnAccountRequest();
            inValue.Body = new SoapApp.Client.ServiceReference1.OpenAnAccountRequestBody();
            inValue.Body.id = id;
            inValue.Body.customerId = customerId;
            inValue.Body.IBAN = IBAN;
            inValue.Body.balance = balance;
            SoapApp.Client.ServiceReference1.OpenAnAccountResponse retVal = ((SoapApp.Client.ServiceReference1.AtmServicesSoap)(this)).OpenAnAccount(inValue);
            return retVal.Body.OpenAnAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapApp.Client.ServiceReference1.OpenAnAccountResponse> SoapApp.Client.ServiceReference1.AtmServicesSoap.OpenAnAccountAsync(SoapApp.Client.ServiceReference1.OpenAnAccountRequest request) {
            return base.Channel.OpenAnAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapApp.Client.ServiceReference1.OpenAnAccountResponse> OpenAnAccountAsync(string id, string customerId, string IBAN, float balance) {
            SoapApp.Client.ServiceReference1.OpenAnAccountRequest inValue = new SoapApp.Client.ServiceReference1.OpenAnAccountRequest();
            inValue.Body = new SoapApp.Client.ServiceReference1.OpenAnAccountRequestBody();
            inValue.Body.id = id;
            inValue.Body.customerId = customerId;
            inValue.Body.IBAN = IBAN;
            inValue.Body.balance = balance;
            return ((SoapApp.Client.ServiceReference1.AtmServicesSoap)(this)).OpenAnAccountAsync(inValue);
        }
    }
}
